### PR TITLE
fix: error in console for txeffect button

### LINKED ISSUE #209: Bug: tab-buttons does not have keys
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `OptionButtons`. See https://reactjs.org/link/warning-keys for more information.
TooltipProvider@http://localhost:5173/node_modules/.vite/deps/@radix-ui_react-tooltip.js?v=88628e8f:543:7
OptionButtons@http://localhost:5173/src/pages/tx-effect-details/tabs.tsx:31:30
```

Image

### PR DESCRIPTION
**Pull request by Mautjee**
closes #209

### CODE REVIEW

File: services/explorer-ui/src/components/custom-tooltip.tsx [hunk 1]
```diff
@@ -0,0 +1,42 @@
+// your-tooltip.jsx
```
Comment (FilipHarald) [inline services/explorer-ui/src/components/custom-tooltip.tsx:1]: remove comment?
