### PR TITLE
fix: Implement two-phase verification for dropped transactions

### LINKED ISSUE #537: bug: not properly handling pending and dropped tx
In the pending tx table pending tx wil be marked dropped even tho they are included in a block

### PR DESCRIPTION
**Pull request by Mautjee**
## Summary
- Resolves race condition where transactions included in blocks were incorrectly flagged as dropped
- Implements two-phase verification system with intermediate `suspected_dropped` state
- Adds dropped transaction verifier service for definitive confirmation
- Prevents false positives for flagging `suspected_dropped` by setting a grace period of 30 sec

## Key Changes
- **Database schema**: Added `suspected_dropped` transaction state
- **Pending TX poller**: Now marks missing transactions as `suspected_dropped` instead of immediately `dropped`
- **Block processing**: Enhanced to check both `pending` and `suspected_dropped` transactions against block contents
- **New verifier service**: Periodic background process that definitively confirms dropped transactions after checking recent blocks
- **Configuration**: Added configurable timing parameters for verification process

### CODE REVIEW

**Comment by Mautjee** [comment]
@claude

File: services/aztec-listener/src/environment.ts [hunk 1]
```diff
@@ -52,6 +52,23 @@ export const AZTEC_DISABLE_ETERNAL_CATCHUP = z.coerce
...
+  .number()
+  .default(300000) // 5 minutes
+  .parse(process.env.DROPPED_TX_AGE_THRESHOLD_MS);
+export const DROPPED_TX_BLOCK_LOOKBACK = z.coerce
+  .number()
+  .default(10)
+  .parse(process.env.DROPPED_TX_BLOCK_LOOKBACK);
+export const MEMPOOL_SYNC_GRACE_PERIOD_MS = z.coerce
+  .number()
+  .default(30000) // 30 seconds
```
Comment (FilipHarald) [inline services/aztec-listener/src/environment.ts:69]:
```suggestion
  .default(30_000) // 30 seconds
```

**Review by FilipHarald — CHANGES_REQUESTED** [review]
Good initial implementation. And it sure seems to work. :+1: 

But there are 1 problem that you have in two places: we do too many queries to our nodes. And it's indeed queries that we shouldn't need to do, because we already have the data.

1. There should not have to be a separate droppedTx poller. Either maybe solve this problem by try to always poll pending txs from the same node. Or, solve it within the existing poller/emission-callback.
2. Querying a bunch of blocks back in time just to check is not optimal. We can merge it like this, but I would then like to know how many queries that is.
