### PR TITLE
bug: fix misalignment of landing page tables

### LINKED ISSUE #395: Landing page tables do not align with each other.
The same amount of entries are shown but the txEffects look way less because the height of each row is different.
Image

### PR DESCRIPTION
**Pull request by Mautjee**
closes #395

### CODE REVIEW

File: services/explorer-ui/src/components/tx-effects/tx-effects-table.tsx [hunk 1]
```diff
@@ -33,16 +33,15 @@ export const TxEffectsTable: FC<Props> = ({
   }
   return (
     <section className="relative mx-0 w-full transition-all">
-      <div className="space-y-4 bg-white rounded-lg p-5">
+      <div className="space-y-4 bg-white rounded-lg p-5 ">
```
Comment (FilipHarald) [inline services/explorer-ui/src/components/tx-effects/tx-effects-table.tsx:36]:
```suggestion
      <div className="space-y-4 bg-white rounded-lg p-5">
```

**Review by FilipHarald — APPROVED** [review]
