### PR TITLE
Fix/timestamp consistency

### LINKED ISSUE #547: bug: inconsistant timestamps in application
Use Data everywhere in the application

### PR DESCRIPTION
**Pull request by WietzeSlagman**
Fixes some inconsistencies in the use of timestamp and how they are stored in the backend.

This PR introduces a util function that forces all timestamps to be in miliseconds, this does assume that there are only 2 lengths of timestamps either 10 or 14.

### CODE REVIEW

File: packages/types/src/aztec/general.ts [hunk 1]
```diff
@@ -91,7 +91,7 @@ export type ChicmozL2Sequencer = z.infer<typeof chicmozL2SequencerSchema>;
 export const chicmozContractInstanceBalanceSchema = z.object({
   contractAddress: aztecAddressSchema,
   balance: z.coerce.bigint().nonnegative(),
-  timestamp: z.coerce.date().default(() => new Date()),
+  timestamp: z.coerce.number().default(() => new Date().valueOf()),
```
Comment (WietzeSlagman) [inline packages/types/src/aztec/general.ts:94]:
```suggestion
  timestamp: z.coerce.number().default(() => new Date().getTime()),
```

consistent with rest of code base
