### PR TITLE
ui: fix the buttons in the ui

### LINKED ISSUE #119: UI pills fix
- Buttons / tabs fix
home page top pills need a little more spacing

### PR DESCRIPTION
**Pull request by Mautjee**
this small pr is to fix the button appearance in the ui

closes #119

### CODE REVIEW

File: services/explorer-ui/src/pages/landing/index.tsx [hunk 1]
```diff
@@ -59,44 +59,40 @@ export const Landing: FC = () => {
...
           {getStatsData(
             loadingTotalEffects24h,
             errorTotalEffects24h,
             totalTxEffects24h,
           )}
         </div>
-        <div className="bg-white w-3/12 rounded-lg shadow-md p-4">
-          <p>Total amount of contracts</p>
+        <div className="bg-white w-96 rounded-lg shadow-md p-4">
+          <p>Total amount of contract</p>
```
Comment (FilipHarald) [inline services/explorer-ui/src/pages/landing/index.tsx:76]:
```suggestion
          <p>Total amount of contracts</p>
```

**Review by FilipHarald — APPROVED** [review]
