### PR TITLE
feat: fix footer an all weird pages

### LINKED ISSUE #145: UI: fix all links and stuff in footer

### PR DESCRIPTION
**Pull request by FilipHarald**
resolves #145

### CODE REVIEW

File: services/explorer-ui/src/pages/about-us.tsx [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+      <div className="bg-white w-full rounded-lg shadow-md p-4 md:w-1/2">
+        <p>
+          We are a team of developers and designers who are passionate about
+          privacy on the internet. We have been building in the crypto space for
+          over 5 years and have a deep understanding of the technology and the
+          community.
+        </p>
+          <br />
+        <p>
+          Since 3 years back we have been building with ZK. And are now building
```
Comment (WietzeSlagman) [inline services/explorer-ui/src/pages/about-us.tsx:16]: i'd replace this part with:

Obscura is a platform dedicated to simplifying the development of privacy-oriented applications on blockchain technology. It provides a solid foundation, offering RPC endpoints, APIs, and SDKs to streamline app development on leading privacy-focused blockchains. These tools are designed to help developers efficiently construct, deploy, and maintain applications that prioritize user privacy, leveraging Obscura's specialized infrastructure.

Comment (FilipHarald) [reply services/explorer-ui/src/pages/about-us.tsx:16]: https://github.com/aztlan-labs/chicmoz/pull/151
